services:
  - type: web
    name: swing-trade-screener
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: TWILIO_TO
        sync: false
    plan: free
